### ISSUE TITLE
Work Done This Week

### ISSUE THREAD

**Issue by norlab** [OpenDataLiteracy/WA-State-Library-2018#1]
This is an excellent way to report on progress! It would be great to have a record of each of the week's work done (both for ODL and for your own record-keeping). Would it be possible to create a new .md file for each week (rather than writing over the document each week)?

**Comment by KathleenSullivan** [comment]
Hey Bree! I'm happy to document any way that you find best, but I figured the "History" (https://github.com/OpenDataLiteracy/WA-State-Library-2018/commits/master/WorkDoneThisWeek.md) of all the versions would provide the report by week.

**Comment by norlab** [comment]
That's great, Kathleen. Versioning works just fine too as long as we're on the same page. Thanks for clarifying!
